spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration

  config:
    activate:
      on-profile: dev
  application:
    name: cliente

  datasource:
    url: jdbc:postgresql://postgres_carstore:5432/FIAP-carStore
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  spring:
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: ""
  logging:
    level:
      org.springframework.security: DEBUG


